### ISSUE TITLE
Typography issues

### ISSUE THREAD

**Issue by jLBasilio** [xendit/xendit-python#35]
In _Retrieve Accessible Accounts by Linked Account Token_ API reference ([link here](https://developers.xendit.co/api-reference/?python#retrieve-accessible-accounts-by-linked-account-token)):

The <code>DirectDebit.get_accessible_<b>account</b>\_by_token()</code> function is actually <code>DirectDebit.get_accessible_<b>accounts</b>\_by_token()</code>.

Please update documents or change the function name itself.

**Comment by stanleynguyen** [comment]
Thanks @jLBasilio for reporting. We will update our API ref. Will notify our docs team
