### ISSUE TITLE
Add metadata object on Credit Card charge creation 

### ISSUE THREAD

**Issue by zakiarsyad** [xendit/xendit-python#48]
Currently, Xendit API for creating a charge allows `metadata` object to be sent in the request payload -> https://developers.xendit.co/api-reference/#create-charge

This library doesn't support `metadata` object yet https://github.com/xendit/xendit-python#create-charge

**Comment by MESMUR** [comment]
Resolved with #49 
Released with https://github.com/xendit/xendit-python/releases/tag/v0.1.7
