### ISSUE TITLE
Invoice object helper

### ISSUE THREAD

**Issue by ashlite** [xendit/xendit-python#57]
So I want to create customer object for the invoice, but in the invoice there is no helper for building customer.
And there is no global customer object in the library.

And in the API, there is **customer_notification_preference** object, but that object is not available in the invoice parameter.

So the library is lagging behind the HTTP API Endpoint.

**Comment by adityarx** [comment]
Hi @ashlite, this response is a little late, but I'm afraid we are a bit resource constrained right now and can't add this to the library. However, if you'd be open to contributing the Customer object to Xendit, we'd be happy to review and release it 🙏
