### ISSUE TITLE
type object 'EWallet' has no attribute 'create_ewallet_charge'

### ISSUE THREAD

**Issue by dimasanwaraziz** [xendit/xendit-python#60]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/50611785/209054669-06d6e217-76ad-4451-b0c3-67285969923b.png">

**Comment by adityarx** [comment]
Hello @dimasanwaraziz, we're sorry you ran into this issue. We're keeping issues on GitHub reserved for active bugs and feature requests for our Python SDK, so we encourage you to have a look at our Docs (https://docs.xendit.co/) or ask for help through the chatbot. Cheers and sorry we couldn't be of help~

**Comment by adityarx** [comment]
@dimasanwaraziz apologies, this was a bug on our end and we've fixed this in release v0.2.2.
