### ISSUE TITLE
Make a request with a proxy?

### ISSUE THREAD

**Issue by aarroisi** [xendit/xendit-python#67]
Hi, is it possible to use this SDK with a proxy address? I'm hosting my server on a dynamic IP-based provision, and want to pass the request to the Xendit with a static IP from a proxy.

**Comment by adityarx** [comment]
Yeap this is possible @aarroisi, you may use this field in the Configuration object https://github.com/xendit/xendit-python/blob/master/xendit/configuration.py#L164

Let us know if it doesn't work 🙏
