### ISSUE TITLE
Invalid minimum python version requirement

### ISSUE THREAD

**Issue by ariksubagia** [xendit/xendit-python#68]
This line use union type, but union type introduced in python 3.10, code that use python 3.9 below will face syntax error on this particular line.
https://github.com/xendit/xendit-python/blame/1207334e6f5a96ae411221c188af1e7c6191ffb2/xendit/invoice/model/address_object.py#L208

your documentation says 3.6 >=.
it cause confusion.

**Comment by adityarx** [comment]
Ah our mistake @ariksubagia, yes the minimum required version is v3.10. We will correct this in our next release, but is this disruptive for your business?

**Comment by ariksubagia** [comment]
yes, its all good now, i've upgraded to 3.10
